backend:
  name: github
  repo: jmantonellini/conforma-web
  branch: main
  base_url: https://decap-proxy-jma.workers.dev
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
